[package]
name = "filer_client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.217"
serde_derive = "1.0.217"
ureq = { version = "2.12.1", features = ["json"] }
ureq_multipart = "1.1.1"
