[package]
name = "filer_client"
version = "0.1.0"
edition = "2021"

[dependencies]
cookie = "0.18.1"
serde = "1.0.217"
serde_derive = "1.0.217"
ureq = { version = "2.12.1", features = ["cookies", "json"] }
ureq_multipart = "1.1.1"
